# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Astral Dynamics
email: contact@astraldynamics.co.uk
description: >
  We are a forward thinking tech company with a focus on enhancing culture
  with technology.
baseurl: ""
url: "http://astraldynamics.co.uk"
license: MIT
license_url: "https://opensource.org/licenses/MIT"
disqus_url: "astraldynamics.disqus.com"
twitter_username: theastralship
github_username: AstralDynamics
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Team
team:
  liam:
    name: Liam Kurmos
    display_name: Liam
    role: Managing Director
    image: http://i.imgur.com/cbPUOWM.jpg?1
    twitter: liamkurmos
    bio: >
      AD is not a conventional company and Liam is not a conventional director.
      His role is largely as a facilitator and an innovator - helping everyone
      on the team get what they need and ensuring everyone is able to work
      together effectively. Externally he represents the company and manages
      relationships with our clients and partners.

      Outside of work Liam loves travelling and exploring new cultures. With
      an optimistic approach he tackles societal and environmental challenges
      and does whatever he can to improve the big picture.

  dan:
    name: Dan Prince
    display_name: Dan
    role: Developer
    image: http://i.imgur.com/q1EsUYL.jpg?1
    web: http://danthedev.com
    twitter: workshydev
    github: danprince
    bio: >
      Dan has been with Astral Dynamics from the beginning - since he met Liam
      at University. Since then, he's worked around his studies to become the
      software development backbone that we've come to depend on for many of
      our projects.

      When he's not working at a computer, Dan is a keen musician and can often
      be found with one of his guitars or tweaking his home recording studio.

  rishabh:
    name: Rishabh Jain
    display_name: Rishabh
    role: Developer
    image: https://avatars1.githubusercontent.com/u/2570363?v=3&s=460
    github: rishabhjain
    bio: >
      Rishabh is the latest addition to our team. He's joined us full time
      after an initial period working remotely from India. His knowledge
      of machine learning has already proved to be a great addition to our
      team.

# Build settings
markdown: kramdown

