# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Astral Dynamics
email: contact@astraldynamics.co.uk
description: Creative Technology
baseurl: ""
url: http://astraldynamics.co.uk
theme_color: "#1b1b1b"
markdown: kramdown
sass:
  style: compressed
collections:
  portfolio:
    output: true
    permalink: /showcase/:path
  jobs:
    output: true
    permalink: /job/:path

